export const deals = [
  {
    id: 1,
    restaurant: "Burger Joint",
    discount: "20% off entire order",
    description: "Get 20% off your entire order at Burger Joint, the best burgers in town!",
    longDescription:
      "Burger Joint offers a wide variety of gourmet burgers made with 100% grass-fed beef and fresh, locally sourced ingredients. With this exclusive student deal, you'll save 20% on your entire order, including sides and drinks.",
    expires: "May 31, 2025",
    logo: "/placeholder.svg?height=80&width=80",
    category: "food",
    isPopular: true,
    price: 8.99,
    value: 11.99,
    location: "123 University Ave",
    rating: 4,
    reviewCount: 128,
    availability: "Mon-Fri, 11am-10pm",
    restaurantId: "rest_123",
    terms: [
      "Valid for dine-in and takeout only",
      "Cannot be combined with other offers",
      "Valid student ID required at redemption",
      "Expires on May 31, 2025",
    ],
    includes: ["20% discount on all menu items", "Valid for up to 4 people", "Includes drinks and sides"],
  },
  {
    id: 2,
    restaurant: "Pizza Palace",
    discount: "Buy one, get one free",
    description: "Buy any large pizza and get a second one of equal or lesser value for free!",
    longDescription:
      "Pizza Palace is known for its authentic Italian pizzas with a wide range of toppings. This BOGO deal lets you enjoy twice the pizza for half the price. Perfect for study groups or sharing with roommates!",
    expires: "June 15, 2025",
    logo: "/placeholder.svg?height=80&width=80",
    category: "food",
    isPopular: true,
    price: 12.99,
    value: 25.98,
    location: "456 College Street",
    rating: 5,
    reviewCount: 203,
    availability: "Every day, 11am-11pm",
    restaurantId: "rest_456",
    terms: [
      "Valid for dine-in, takeout, and delivery",
      "Free pizza must be of equal or lesser value",
      "Valid student ID required at redemption",
      "Expires on June 15, 2025",
    ],
    includes: [
      "Buy one large pizza, get one free",
      "All toppings and specialty pizzas included",
      "Valid any day of the week",
    ],
  },
  {
    id: 3,
    restaurant: "Sushi Spot",
    discount: "$5 off orders over $25",
    description: "Enjoy $5 off your order when you spend $25 or more at Sushi Spot!",
    longDescription:
      "Sushi Spot offers the freshest sushi and Japanese cuisine in town. With this deal, you'll save $5 on your order when you spend $25 or more, making it perfect for lunch or dinner with friends.",
    expires: "May 20, 2025",
    logo: "/placeholder.svg?height=80&width=80",
    category: "food",
    isPopular: false,
    price: 3.99,
    value: 5.0,
    location: "789 Campus Drive",
    rating: 4,
    reviewCount: 87,
    availability: "Tue-Sun, 12pm-9pm",
    restaurantId: "rest_789",
    terms: [
      "Minimum purchase of $25 required",
      "Valid for dine-in only",
      "Cannot be combined with other offers",
      "Expires on May 20, 2025",
    ],
    includes: ["$5 discount on orders over $25", "Valid for all menu items", "One coupon per table"],
  },
  {
    id: 4,
    restaurant: "Coffee House",
    discount: "Free upgrade to large",
    description: "Get a free size upgrade on any coffee or tea at Coffee House!",
    longDescription:
      "Coffee House is the perfect spot to study or hang out with friends. With this deal, you can enjoy more of your favorite coffee or tea with a free upgrade to a large size. Perfect for those long study sessions!",
    expires: "Ongoing",
    logo: "/placeholder.svg?height=80&width=80",
    category: "drinks",
    isPopular: true,
    price: 1.99,
    value: 3.5,
    location: "321 Scholar Street",
    rating: 5,
    reviewCount: 156,
    availability: "Every day, 6am-10pm",
    restaurantId: "rest_321",
    terms: [
      "Valid for all coffee and tea drinks",
      "Not valid for specialty drinks or frappuccinos",
      "Valid student ID required at redemption",
      "No expiration date",
    ],
    includes: [
      "Free size upgrade (small to medium or medium to large)",
      "Valid for coffee and tea only",
      "Unlimited use",
    ],
  },
  {
    id: 5,
    restaurant: "Smoothie Bar",
    discount: "50% off second smoothie",
    description: "Buy one smoothie, get 50% off your second smoothie at Smoothie Bar!",
    longDescription:
      "Smoothie Bar offers delicious and nutritious smoothies made with fresh fruits and vegetables. With this deal, you can enjoy a second smoothie at half price when you buy one at regular price.",
    expires: "June 30, 2025",
    logo: "/placeholder.svg?height=80&width=80",
    category: "drinks",
    isPopular: false,
    price: 4.99,
    value: 7.5,
    location: "555 Fitness Avenue",
    rating: 4,
    reviewCount: 92,
    availability: "Mon-Sat, 8am-8pm",
    restaurantId: "rest_555",
    terms: [
      "Second smoothie must be of equal or lesser value",
      "Valid for in-store purchases only",
      "Cannot be combined with other offers",
      "Expires on June 30, 2025",
    ],
    includes: [
      "50% off second smoothie with purchase of first smoothie at regular price",
      "Valid for all smoothie flavors and sizes",
      "Add-ons not included in discount",
    ],
  },
  {
    id: 6,
    restaurant: "Taco Tuesday",
    discount: "$1 tacos on Tuesdays",
    description: "Enjoy $1 tacos every Tuesday at Taco Tuesday restaurant!",
    longDescription:
      "Taco Tuesday restaurant offers authentic Mexican cuisine at affordable prices. With this exclusive student deal, you can enjoy delicious tacos for just $1 each every Tuesday. Choose from a variety of fillings including beef, chicken, and vegetarian options.",
    expires: "Ongoing",
    logo: "/placeholder.svg?height=80&width=80",
    category: "food",
    isPopular: true,
    price: 2.99,
    value: 5.0,
    location: "777 Fiesta Street",
    rating: 4,
    reviewCount: 175,
    availability: "Tuesdays only, 11am-10pm",
    restaurantId: "rest_777",
    terms: [
      "Valid on Tuesdays only",
      "Maximum of 6 tacos per student",
      "Valid student ID required at redemption",
      "Dine-in only",
    ],
    includes: [
      "$1 tacos (regular price $2.50 each)",
      "Choice of beef, chicken, or vegetarian fillings",
      "Valid every Tuesday",
    ],
  },
  {
    id: 7,
    restaurant: "Movie Theater",
    discount: "Student night: $5 tickets",
    description: "Enjoy $5 movie tickets every Thursday night with your student ID!",
    longDescription:
      "Take a break from studying and enjoy the latest blockbusters at a fraction of the cost. Every Thursday night is student night at the Movie Theater, where you can watch any movie for just $5 with your valid student ID.",
    expires: "Ongoing",
    logo: "/placeholder.svg?height=80&width=80",
    category: "entertainment",
    isPopular: true,
    price: 5.99,
    value: 12.5,
    location: "888 Cinema Boulevard",
    rating: 5,
    reviewCount: 210,
    availability: "Thursdays only, 6pm-close",
    restaurantId: "rest_888",
    terms: [
      "Valid on Thursdays only",
      "Valid for standard screenings only (not valid for IMAX, 3D, or special events)",
      "Valid student ID required at box office",
      "One ticket per student ID",
    ],
    includes: [
      "$5 movie ticket (regular price $12.50)",
      "Valid for any standard screening",
      "Valid every Thursday night",
    ],
  },
  {
    id: 8,
    restaurant: "Bowling Alley",
    discount: "2 games + shoe rental for $10",
    description: "Get 2 games of bowling plus shoe rental for just $10 at the Bowling Alley!",
    longDescription:
      "Looking for a fun activity with friends? Head to the Bowling Alley where students can enjoy 2 games of bowling plus shoe rental for just $10. That's less than half the regular price!",
    expires: "July 31, 2025",
    logo: "/placeholder.svg?height=80&width=80",
    category: "entertainment",
    isPopular: false,
    price: 9.99,
    value: 22.0,
    location: "999 Strike Lane",
    rating: 4,
    reviewCount: 68,
    availability: "Sun-Thu, all day",
    restaurantId: "rest_999",
    terms: [
      "Valid Sunday through Thursday only",
      "Not valid on holidays or during league play",
      "Valid student ID required",
      "Expires on July 31, 2025",
    ],
    includes: ["2 games of bowling", "Shoe rental", "Valid Sunday through Thursday"],
  },
]
